# -*- coding: utf-8 -*-
"""P3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9SgVS6HMvCQskOPOPozqMy2_d3PdHeK

#Project 3
Written by Cricket Bergner

Started: 3/10/26

Ended: 3/??/26
"""

# import and functions
################################################################################

# import libraries
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import odeint, solve_ivp

# derivative functions (adjusted for damped and undamped)
def accel(x, v, omega, damping):
    return -omega**2*x - damping*v

def deriv_ivp(t, N, omega, damping):
    x, v = N
    dxdt = v
    dvdt = -omega**2*x - damping*v
    return [dxdt, dvdt]

def deriv_odeint(N, t, omega, damping):
    x, v = N
    dxdt = v
    dvdt = -omega**2*x - damping*v
    return [dxdt, dvdt]

# Scipy Method
def scipy_method(N_initial, tmin, tmax, nts, deriv):
    t = np.linspace(tmin, tmax, nts)
    N = odeint(deriv, N_initial, t)
    x = N[:,0]
    v = N[:,1]

    return t, x, v

# RK4(5) scipy function
def RK45_method(N_initial, tmin, tmax, nts, deriv):
  t = np.linspace(tmin, tmax, nts)
  sol = solve_ivp(deriv, (tmin, tmax), N_initial, method='RK45', t_eval=t)
  x = sol.y[0]
  v = sol.y[1]

  return t, x, v

# Verlet-velocity sympletic integrator functions
def verlet(N_initial, tmin, tmax, nts, deriv):

  # define inital variables
  x0, v0 = N_initial
  x = np.zeros(nts + 1)
  v = np.zeros(nts + 1)
  x[0] = x0
  v[0] = v0
  t = np.linspace(tmin, tmax, nts + 1)
  dt = t[1] - t[0]

  # loop
  for i in range(nts):
    a = deriv(x[i], v[i])
    v_half = v[i] + 0.5 * dt * a
    x[i+1] = x[i] + dt * v_half
    a_new = deriv(x[i+1], v_half)
    v[i+1] = v_half + 0.5 * dt * a_new

  return t, x, v

################################################################################

# For a simple harmonic oscillator not at rest, what
# shape will it trace out in phase space?
################################################################################

# define initial variables
m = 1
k = 3
b = 0 # undamped
omega = np.sqrt(k/m)
damping = 0
nts = 1024 # larger nts, better approximation

N_initial = [1, 0]
tmin = 0
tmax = 10

# call the integrators
t_s, x_s, v_s = scipy_method(N_initial, tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, omega, damping))
t_r, x_r, v_r = RK45_method(N_initial, tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, omega, damping))
t_v, x_v, v_v = verlet(N_initial, tmin, tmax, nts, lambda x, v: accel(x, v, omega, damping))

# make the plots
plt.plot(v_r, x_r, color = '#f37fb0', label = "RK4", linewidth = 10)
plt.plot(v_v, x_v, 'o', color = '#61dbb0', label = "Verlet")
plt.plot(v_s, x_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

print("The shape the simple harmonic oscillator will trace out in phase space is an ellipse. Note that all the integration methods were passed")
print("different initial variables. This shows even with different initial conditions the phase space will always show an ellipse.")
print("")

################################################################################
# How does a SHM evolve with a linear damping term?
################################################################################

# damping term added
damping = 0.2 / m

N_initial = [1, 0]
tmin = 0
tmax = 100

# call the integrators
nt_s, nx_s, nv_s = scipy_method(N_initial, tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, omega, damping))
nt_r, nx_r, nv_r = RK45_method(N_initial, tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, omega, damping))
nt_v, nx_v, nv_v = verlet(N_initial, tmin, tmax, nts, lambda x, v: accel(x, v, omega, damping))

# make the plots
plt.plot(nv_r, nx_r, 'o', color = '#f37fb0', label = "RK4")
plt.plot(nv_v, nx_v, color = '#61dbb0', label = "Verlet")
plt.plot(nv_s, nx_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator with Damping Term")
plt.legend()
plt.show()
print("")

print("The SHO evolves into a spiral.")
print("")

################################################################################
# How does the total mechanical energy (T+V) change over time with different
# solvers (see below) in these two cases?
################################################################################

# total mechanical energy
E_r = 0.5*m*v_r**2 + 0.5*k*x_r**2
E_v = 0.5*m*v_v**2 + 0.5*k*x_v**2
E_s = 0.5*m*v_s**2 + 0.5*k*x_s**2

nE_r = 0.5*m*nv_r**2 + 0.5*k*nx_r**2
nE_v = 0.5*m*nv_v**2 + 0.5*k*nx_v**2
nE_s = 0.5*m*nv_s**2 + 0.5*k*nx_s**2

# make the plots
plt.plot(t_r, E_r, color = '#f37fb0', label = "RK4")
plt.plot(t_v[:nts], E_v[:nts], color = '#61dbb0', label = "Verlet")
plt.plot(t_s, E_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time")
plt.legend()
plt.show()
print("")

plt.plot(nt_r, nE_r, 'o', color = '#f37fb0', label = "RK4")
plt.plot(nt_v, nE_v, color = '#61dbb0', label = "Verlet")
plt.plot(nt_s, nE_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time (Damped)")
plt.legend()
plt.show()
print("")

print("The total mechanical energy decreases over time for the oscillator, though it still oscillates around the origin.")
print("The total mechanical energy decreases over time for the damped oscillator, like a decaying exponential.")
print("")

################################################################################
# Extension 1
################################################################################

# define step change, initial arrays, and points
delta = 0.01
x0 = 1
v0 = 2
pts = [(x0, v0), (x0 + delta, v0), (x0 + delta, v0 + delta), (x0, v0 + delta)]

straj = [] # short for scipy trajectories (undamped)
rtraj = []
vtraj = []
sarea = []
rarea = []
varea = []

straj_d = [] # damped
rtraj_d = []
vtraj_d = []
sarea_d = []
rarea_d = []
varea_d = []

for (x0, v0) in pts: # evolving each pt with the integrators
  # undamped
  st, sx, sv = scipy_method([x0, v0], tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, np.sqrt(3/1), 0))
  straj.append((sx, sv))
  rt, rx, rv = RK45_method([x0, v0], tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, np.sqrt(3/1), 0))
  rtraj.append((rx, rv))
  vt, vx, vv = verlet([x0, v0], tmin, tmax, nts, lambda x, v: accel(x, v, np.sqrt(3/1), 0))
  vtraj.append((vx, vv))

  # damped
  st_d, sx_d, sv_d = scipy_method([x0, v0], tmin, tmax, nts, lambda N, t_odeint: deriv_odeint(N, t_odeint, np.sqrt(3/1), 0.2))
  straj_d.append((sx_d, sv_d))
  rt_d, rx_d, rv_d = RK45_method([x0, v0], tmin, tmax, nts, lambda t_ivp, N_ivp: deriv_ivp(t_ivp, N_ivp, np.sqrt(3/1), 0.2))
  rtraj_d.append((rx_d, rv_d))
  vt_d, vx_d, vv_d = verlet([x0, v0], tmin, tmax, nts, lambda x, v: accel(x, v, np.sqrt(3/1), 0.2))
  vtraj_d.append((vx_d, vv_d))

# area calculations (can't pass in nts because verlet returns a different number of values)
def calculate_area(traj):
    nts = len(traj[0][0])
    areas = np.zeros(nts)
    for i in range(nts):
        # Extract the 4 points at time index i
        p1 = [traj[0][0][i], traj[0][1][i]]
        p2 = [traj[1][0][i], traj[1][1][i]]
        p3 = [traj[2][0][i], traj[2][1][i]]
        p4 = [traj[3][0][i], traj[3][1][i]]

        # Shoelace formula
        x = [p1[0], p2[0], p3[0], p4[0]]
        v = [p1[1], p2[1], p3[1], p4[1]]

        area = 0.5 * np.abs(np.dot(x, np.roll(v, 1)) - np.dot(v, np.roll(x, 1)))
        areas[i] = area
    return areas

# After your loop that fills strag, rtrag, vtrag:
sarea = calculate_area(straj)
rarea = calculate_area(rtraj)
varea = calculate_area(vtraj)

sarea_d = calculate_area(straj_d)
rarea_d = calculate_area(rtraj_d)
varea_d = calculate_area(vtraj_d)

# plot undamped
plt.plot(st, sarea, color = 'red', label="Scipy")
plt.plot(rt, rarea, color = 'green', label="RK45")
plt.plot(vt, varea, color = 'blue', label="Verlet")

plt.xlabel("Time")
plt.ylabel("Phase Space Area")
plt.title("Not Damped Osciallator")
plt.legend()
plt.show()
print("")

# plot damped
plt.plot(st_d, sarea_d, 'o', color = 'red', label="Scipy")
plt.plot(rt_d, rarea_d, color = 'green', label="RK45")
plt.plot(vt_d, varea_d, '--', color = 'blue', label="Verlet")

plt.xlabel("Time")
plt.ylabel("Phase Space Area")
plt.title("Damped Oscillator")
plt.legend()
plt.show()

################################################################################
# Meshgrid
################################################################################

