# -*- coding: utf-8 -*-
"""P3D1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB_ExJHGGagS3KHdYGT90zrCSqWFot_C
"""

# Project 3 Draft 1 code
# Written by Cricket Bergner
# 03/10/26

# import libraries
import matplotlib.pyplot as plt
import numpy as np
import math
from scipy.integrate import odeint, solve_ivp
#from prettytable import PrettyTable as pt

# integration functions from previous notebooks

# RK2 Method
def RK2(N_initial, tmin, tmax, nts, deriv):

    # define initial variables
    N = np.zeros(nts + 1)
    N[0] = N_initial
    t = np.linspace(tmin, tmax, nts + 1)
    dt = t[1] - t[0]

    # loop the first and second substep
    for it in range(0, nts):
        N_half = N[it] + (dt / 2) * deriv(N[it], t[it])
        N[it+1] = N[it] + dt * deriv(N_half, t[it] + dt/2)

    return t, N

# Euler Method
def Euler_solver(N_initial, tmin, tmax, nts, deriv):

    # define initial variables
    N = np.zeros(nts + 1)
    N[0] = N_initial
    t = np.linspace(tmin, tmax, nts + 1)
    dt = t[1] - t[0]

    # loop
    for it in range(0,nts):
        N[it+1] = N[it] + dt * deriv(N[it], t[it])

    return t, N

# Scipy Method (updated for SHO)
def scipy_method(N_initial, tmin, tmax, nts, deriv):

    t = np.linspace(tmin, tmax, nts)
    N = odeint(deriv, N_initial, t)
    x = N[:,0]
    v = N[:,1]

    return t, x, v

# RK4(5) scipy function

def RK45_method(N_initial, tmin, tmax, nts, deriv):
  t = np.linspace(tmin, tmax, nts)

  sol = solve_ivp(deriv, (tmin, tmax), N_initial, method='RK45', t_eval=t)

  x = sol.y[0]
  v = sol.y[1]

  return t, x, v

"""Time Complexity: O(n), where n is (x-x0)/h.
Auxiliary Space: O(1) as constant space for variables is being used

source: https://www.geeksforgeeks.org/dsa/runge-kutta-4th-order-method-solve-differential-equation/
"""

# Verlet-velocity sympletic integrator

def accel(x, t):
    return -(k/m)*x

def verlet(N_initial, tmin, tmax, nts, deriv):

  # define inital variables
  x0, v0 = N_initial
  x = np.zeros(nts + 1)
  v = np.zeros(nts + 1)
  x[0] = x0
  v[0] = v0
  t = np.linspace(tmin, tmax, nts + 1)
  dt = t[1] - t[0]

  # loop
  for i in range(nts):
    a = deriv(x[i], t[i])
    v_half = v[i] + 0.5 * dt * a
    x[i+1] = x[i] + dt * v_half
    a_new = deriv(x[i+1], t[i+1])
    v[i+1] = v_half + 0.5 * dt * a_new

  return t, x, v

"""https://stackoverflow.com/questions/29009771/verlet-algorithm-implementation-in-python"""

# For a simple harmonic oscillator not at rest, what shape will it trace out in phase space?

# deriv functions
def deriv_ivp(t, N):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x
    return [dxdt, dvdt]

def deriv_odeint(N, t):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x
    return [dxdt, dvdt]

# define initial variables
m = 1
k = 3
omega = np.sqrt(k/m)
nts = 1024 # larger nts, better approximation

N_initial = [1, 0]
tmin = 0
tmax = 10

# call the integrators
t_s, x_s, v_s = scipy_method(N_initial, tmin, tmax, nts, deriv_odeint)
t_r, x_r, v_r = RK45_method(N_initial, tmin, tmax, nts, deriv_ivp)
t_v, x_v, v_v = verlet(N_initial, tmin, tmax, nts, accel)

# make the plots

plt.plot(v_r, x_r, color = '#f37fb0', label = "RK4")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

plt.plot(v_v, x_v, color = '#61dbb0', label = "Verlet")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

plt.plot(v_s, x_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

print("")
print("The shape the simple harmonic osciallator will trace out in phase space is an ellipse.")

# How does a SHM evolve with a linear damping term?

# How does the total mechanical energy (T+V) change over time with different solvers (see below) in these two cases?