# -*- coding: utf-8 -*-
"""P3D1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VB_ExJHGGagS3KHdYGT90zrCSqWFot_C
"""

# Project 3 Draft 1 code
# Written by Cricket Bergner
# 03/10/26

# import libraries
import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import odeint, solve_ivp

# Scipy Method (updated for SHO)
def scipy_method(N_initial, tmin, tmax, nts, deriv):

    t = np.linspace(tmin, tmax, nts)
    N = odeint(deriv, N_initial, t)
    x = N[:,0]
    v = N[:,1]

    return t, x, v

# RK4(5) scipy function

def RK45_method(N_initial, tmin, tmax, nts, deriv):
  t = np.linspace(tmin, tmax, nts)

  sol = solve_ivp(deriv, (tmin, tmax), N_initial, method='RK45', t_eval=t)

  x = sol.y[0]
  v = sol.y[1]

  return t, x, v

# Verlet-velocity sympletic integrator

def accel(x, t):
    return -(k/m)*x

def verlet(N_initial, tmin, tmax, nts, deriv):

  # define inital variables
  x0, v0 = N_initial
  x = np.zeros(nts + 1)
  v = np.zeros(nts + 1)
  x[0] = x0
  v[0] = v0
  t = np.linspace(tmin, tmax, nts + 1)
  dt = t[1] - t[0]

  # loop
  for i in range(nts):
    a = deriv(x[i], t[i])
    v_half = v[i] + 0.5 * dt * a
    x[i+1] = x[i] + dt * v_half
    a_new = deriv(x[i+1], t[i+1])
    v[i+1] = v_half + 0.5 * dt * a_new

  return t, x, v

# For a simple harmonic oscillator not at rest, what shape will it trace out in phase space?

# deriv functions
def deriv_ivp(t, N):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x
    return [dxdt, dvdt]

def deriv_odeint(N, t):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x
    return [dxdt, dvdt]

# define initial variables
m = 1
k = 3
omega = np.sqrt(k/m)
nts = 1024 # larger nts, better approximation

N_initial = [1, 0]
tmin = 0
tmax = 10

# call the integrators
t_s, x_s, v_s = scipy_method(N_initial, tmin, tmax, nts, deriv_odeint)
t_r, x_r, v_r = RK45_method(N_initial, tmin, tmax, nts, deriv_ivp)
t_v, x_v, v_v = verlet(N_initial, tmin, tmax, nts, accel)

# make the plots

plt.plot(v_r, x_r, color = '#f37fb0', label = "RK4", linewidth = 10)
plt.plot(v_v, x_v, 'o', color = '#61dbb0', label = "Verlet")
plt.plot(v_s, x_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator")
plt.legend()
plt.show()
print("")

print("The shape the simple harmonic oscillator will trace out in phase space is an ellipse. Note that all the integration methods were passed")
print("different initial variables. This shows even with different initial conditions the phase space will always show an ellipse.")
print("")

# How does a SHM evolve with a linear damping term?

# rewriting deriv and accel functions to fit damping term
# derivative functions will need a damping term in the derivative
def nderiv_ivp(t, N):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x - (b/m)*v
    return [dxdt, dvdt]

def nderiv_odeint(N, t):
    x, v = N
    dxdt = v
    dvdt = -(k/m)*x - (b/m)*v
    return [dxdt, dvdt]

# acceleration term will include velocity
def naccel(x, v):
    return -(k/m)*x - (b/m)*v

# updating verlet
def verlet(N_initial, tmin, tmax, nts, deriv):

  # define inital variables
  x0, v0 = N_initial
  x = np.zeros(nts + 1)
  v = np.zeros(nts + 1)
  x[0] = x0
  v[0] = v0
  t = np.linspace(tmin, tmax, nts + 1)
  dt = t[1] - t[0]

  # loop
  for i in range(nts):
    a = deriv(x[i], v[i])
    v_half = v[i] + 0.5 * dt * a
    x[i+1] = x[i] + dt * v_half
    a_new = deriv(x[i+1], v[i+1])
    v[i+1] = v_half + 0.5 * dt * a_new

  return t, x, v

# everything else will stay the same, but with a b term added
m = 1
k = 3
b = 0.2
omega = np.sqrt(k/m)
nts = 1024 # larger nts, better approximation

N_initial = [1, 0]
tmin = 0
tmax = 100

# call the integrators
nt_s, nx_s, nv_s = scipy_method(N_initial, tmin, tmax, nts, nderiv_odeint)
nt_r, nx_r, nv_r = RK45_method(N_initial, tmin, tmax, nts, nderiv_ivp)
nt_v, nx_v, nv_v = verlet(N_initial, tmin, tmax, nts, naccel)

# make the plots
plt.plot(nv_r, nx_r, 'o', color = '#f37fb0', label = "RK4")
plt.plot(nv_v, nx_v, color = '#61dbb0', label = "Verlet")
plt.plot(nv_s, nx_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Velocity (m/s)")
plt.ylabel("Position (m)")
plt.title("Phase Space of a Harmonic Oscillator with Damping Term")
plt.legend()
plt.show()
print("")

print("The SHO evolves into a spiral.")
print("")

# How does the total mechanical energy (T+V) change over time with different solvers (see below) in these two cases?

# total mechanical energy
E_r = 0.5*m*v_r**2 + 0.5*k*x_r**2
E_v = 0.5*m*v_v**2 + 0.5*k*x_v**2
E_s = 0.5*m*v_s**2 + 0.5*k*x_s**2

nE_r = 0.5*m*nv_r**2 + 0.5*k*nx_r**2
nE_v = 0.5*m*nv_v**2 + 0.5*k*nx_v**2
nE_s = 0.5*m*nv_s**2 + 0.5*k*nx_s**2

# make the plots
plt.plot(t_r, E_r, color = '#f37fb0', label = "RK4")
plt.plot(t_v[:nts], E_v[:nts], color = '#61dbb0', label = "Verlet")
plt.plot(t_s, E_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time")
plt.legend()
plt.show()
print("")

plt.plot(nt_r, nE_r, 'o', color = '#f37fb0', label = "RK4")
plt.plot(nt_v, nE_v, color = '#61dbb0', label = "Verlet")
plt.plot(nt_s, nE_s, color = '#6316b0', label = "Scipy")
plt.xlabel("Time (s)")
plt.ylabel("Energy (J)")
plt.title("Total Mechanical Energy Over Time (Damped)")
plt.legend()
plt.show()
print("")

print("The total mechanical energy decreases over time for the oscillator, though it still oscillates around the origin.")
print("The total mechanical energy decreases over time for the damped oscillator, like a decaying exponential.")
print("")